language: php

php:

  - 5.6

before_install:
  - composer self-update
  - composer create-project laravel/laravel:5.1
  - cd ./laravel
  - composer config repositories.alevento git https://github.com/alevento/composer
  - composer require padosoft/composer dev-master
  - ./vendor/padosoft/composer/tests/sedCommand.sh
  - composer update
  - rm ./config/app.php
  - cp ./vendor/padosoft/composer/tests/app.php ./config
  - rm ./.env.dist
  - cp ./vendor/padosoft/composer/tests/.env.dist ./.env
  - php artisan vendor:publish
  - gem install mailcatcher
  - mailcatcher

script:
  - vendor/bin/phpunit --configuration ./vendor/padosoft/composer/phpunit.xml.dist --testsuite Package --coverage-text --coverage-clover=coverage.clover


