language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: LARAVEL_VERSION=5.0
  - php: 5.5
    env: LARAVEL_VERSION=5.1
  - php: 5.6
    env: LARAVEL_VERSION=5.0
  - php: 5.6
    env: LARAVEL_VERSION=5.1
  - php: 5.6
    env: LARAVEL_VERSION=5.2.23
  - php: 7.0
    env: LARAVEL_VERSION=5.0
  - php: 7.0
    env: LARAVEL_VERSION=5.1
  - php: 7.0
    env: LARAVEL_VERSION=5.2.23
  - php: 7.0
    env: LARAVEL_VERSION=5.3
  - php: 7.1
    env: LARAVEL_VERSION=5.1
  - php: 7.1
    env: LARAVEL_VERSION=5.2.23
  - php: 7.1
    env: LARAVEL_VERSION=5.3

  allow_failures:
  - php: 5.4
    env: LARAVEL_VERSION=5.0
  - php: 5.5
    env: LARAVEL_VERSION=5.0
  - php: 5.6
    env: LARAVEL_VERSION=5.0
  - php: 7.0
    env: LARAVEL_VERSION=5.0
  - php: 7.1
    env: LARAVEL_VERSION=5.0

before_install:
- composer self-update
- if [[ $LARAVEL_VERSION != '5.3' ]]; then composer create-project laravel/laravel:$LARAVEL_VERSION; fi
- if [[ $LARAVEL_VERSION == '5.3' ]]; then composer create-project laravel/laravel:$LARAVEL_VERSION --stability dev; fi
- composer update
- cd ./laravel
- if [[ $LARAVEL_VERSION != '5.3' ]]; then composer require padosoft/laravel-test:1.*; fi
- if [[ $LARAVEL_VERSION == '5.3' && $TRAVIS_PHP_VERSION == 7.0 ]]; then composer require padosoft/laravel-test:2.*; fi
- if [[ $LARAVEL_VERSION == '5.3' && $TRAVIS_PHP_VERSION == 7.1 ]]; then composer require padosoft/laravel-test:2.*; fi
- composer require padosoft/laravel-composer-security dev-master
- if [[ $LARAVEL_VERSION == '5.0' ]]; then composer require mockery/mockery; fi
- chmod 777 -R ./
- "./vendor/padosoft/laravel-composer-security/tests/config/sedCommand.sh"
- composer update
- "./vendor/padosoft/laravel-composer-security/tests/config/sedCommandProvider.sh"
- rm ./.env
- cp ./vendor/padosoft/laravel-composer-security/tests/config/.env.dist ./.env
- php artisan vendor:publish
- rvm 1.9.3 do gem install mime-types -v 2.6.2
- gem install mailcatcher
- mailcatcher
script:
- vendor/bin/phpunit --configuration ./vendor/padosoft/laravel-composer-security/phpunit.xml.dist --testsuite Package --coverage-text --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- if [[ $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != '7.1' ]]; then php ocular.phar code-coverage:upload --access-token="93bdd4aee7a5446ac53fe372f1526b6a3d8af949ec675ab1963ca12398a4eebd" --format=php-clover coverage.clover; fi

notifications:
  email:
    recipients:
        - helpdesk@padosoft.com
        - lorenzo.padovani@padosoft.com
    on_success: always
    on_failure: always
  slack:
    secure: dqmuPu/bIHfgvtNZI43yRnnvpqQ5GclrJcuiXGSeuok00dP0KoATDJRSgYQHp5B9wlwQeOLuc+9JiHq2WAB1VyOO1pdl8GWkUKE1FruI+8+NPbGl8OdxVVi100Vo31Q8NCG1Twd5iK+LPSjqt9v3fOVygL7QnRBFqvPgY/llmIkwjT+zZdNUaxO3fyn04C9ZiPNS1R2zJ67LgnSJogClmfyB2IkZZKOLyOSko4BAyxLymfE7z/5Mf4GTTAgX35K9y/8vubxaedjnVpk4LjvNYwgorzI/k9O+B/Cr5fSlYsHXLQ8zOn4VvoRuEKARZCQImglSpwEGhJtl0HI940YoSwvdpXj5ZbKyskYrg8DtCLPY3+PkBbg7hfWwqQPKGEJrDuhcHF5FGBOJeX8Oihi+27vOThlOTwYHVEAkGLvQ79HPhXhY7wB2vl/eqnLp1iczPbtpDp3PF7lMGW5YQ70aw+4hXxVMusltz+EcsnZNtcydFgdBbUiGmbAnygjMuFouJwtpo9kHmz7Niks7QL4pj/oq9fyYYfOSvuzQI/0LuJlMLfAw73eQqsLtHtNUnU+s5/fsRM8tiTi5HX3sWZWKiPi0IzU0C+OommwoyxxeOvlXxZkGRDbt/qimaOwkfZxKifEzZ2F5gg2gXbHEjSU3vf0X9UHafew7dhWx5XBthog=
    on_success: always
    on_failure: always
