language: php

php:

    - 5.5
    - 5.6
    - 7.0

before_install:
  - composer self-update
  - composer create-project laravel/laravel:5.1
  - cd ./laravel
  - composer config repositories.alevento git https://github.com/alevento/composer
  - composer require padosoft/composer dev-master
  - ./vendor/padosoft/composer/tests/config/sedCommand.sh
  - composer update
  - rm ./config/app.php
  - cp ./vendor/padosoft/composer/tests/config/app.php ./config
  - rm ./.env
  - cp ./vendor/padosoft/composer/tests/config/.env.dist ./.env
  - php artisan vendor:publish
  - gem install mailcatcher
  - mailcatcher

script:
  - vendor/bin/phpunit --configuration ./vendor/padosoft/composer/phpunit.xml.dist --testsuite Package --coverage-text --coverage-clover=coverage.clover


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION != '7.0' ]]; then php ocular.phar code-coverage:upload --access-token="93bdd4aee7a5446ac53fe372f1526b6a3d8af949ec675ab1963ca12398a4eebd" --format=php-clover coverage.clover; fi

