language: php

php:

  - 5.6

before_install:
  - composer self-update
  - composer create-project laravel/laravel:5.1
  - cd ./laravel
  - composer config repositories.alevento git https://github.com/alevento/composer
  - composer require padosoft/composer dev-master
  - /bin/bash ./vendor/padosoft/composer/tests/sedCommand
  - composer update

script:
  - vendor/bin/phpunit --configuration ./vendor/padosoft/composer/phpunit.xml.dist --testsuite Package --coverage-text --coverage-clover=coverage.clover


