language: php

php:

  - 5.5

before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.alevento git https://github.com/alevento/laravel-composer-security
  - composer require padosoft/laravel-composer-security dev-master
  - php artisan vendor:publish

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover


